DROP TABLE IF EXISTS genre cascade;
DROP TABLE IF EXISTS films_genre cascade;
DROP TABLE IF EXISTS USERS cascade;
DROP TABLE IF EXISTS Films cascade;
DROP TABLE IF EXISTS USER_FRENDS cascade;
DROP TABLE IF EXISTS films_likes cascade;
DROP TABLE IF EXISTS rating cascade;


CREATE TABLE IF NOT EXISTS genre(
id_genre integer  PRIMARY KEY,
name varchar(55));

CREATE TABLE IF NOT EXISTS rating (
id_rating integer  PRIMARY KEY,
name varchar(55));

CREATE TABLE IF NOT EXISTS USERS (
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(255) NOT NULL,
login varchar(50) NOT NULL,
name varchar(50),
birthday datetime);

CREATE TABLE IF NOT EXISTS Films(
id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(255), 
description varchar(1000),
duration int,
releaseDate datetime,
rating integer REFERENCES rating(id_rating));

CREATE TABLE FILMS_GENRE (
id_films integer REFERENCES films(id),
id_genre integer REFERENCES genre(id_genre));

CREATE TABLE IF NOT EXISTS USER_FRENDS (
USER_id integer REFERENCES users(id),
USER_friends_id integer REFERENCES users(id),
CONSTRAINT constraint_name UNIQUE (USER_id, USER_friends_id));


CREATE TABLE IF NOT EXISTS films_likes (
film_id integer NOT NULL REFERENCES films(id),
user_id integer NOT NULL REFERENCES users(id),
CONSTRAINT constraint_name_likes UNIQUE (film_id, user_id));
